name: Build Library

on: [push]

env:
  EM_VERSION: 2.0.23
  EM_CACHE_FOLDER: 'emsdk-cache'

jobs:
  buildOnMac:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - run: curl -O -L http://ftpmirror.gnu.org/automake/automake-1.15.tar.gz && tar -zxf automake-1.15.tar.gz && cd automake-1.15 && ./configure && make && make install
    - run: chmod +x ./build_unix.sh && . ./build_unix.sh mac
    - name: Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          library/full/libopenjtalk.dylib
          library/lang/libopenjtalk-lang.dylib

  buildOnLinux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: sudo apt-get install csh -y && curl -O -L http://ftpmirror.gnu.org/automake/automake-1.15.tar.gz && tar -zxf automake-1.15.tar.gz && cd automake-1.15 && ./configure && make && sudo make install
    - run: chmod +x ./build_unix.sh && . ./build_unix.sh linux
    - name: Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          library/full/libopenjtalk.so
          library/lang/libopenjtalk-lang.so

  buildOnWindows:
    runs-on: windows-latest

    strategy:
      matrix:
        include:
          - arch: amd64
            name: x64
          - arch: amd64_x86
            name: x86

    steps:
      - uses: actions/checkout@v2
      - uses: ilammy/msvc-dev-cmd@v1.9.0
        with:
          arch: ${{ matrix.arch }}
      - run: git submodule update --init; cd hts_engine_API; nmake /f Makefile.mak hts_lib
      - run: nmake /f Makefile.mak
      - run: ren library\full\open_jtalk.dll ${{ matrix.name }}_open_jtalk.dll ; cp library\full\${{ matrix.name }}_open_jtalk.dll ${{ matrix.name }}_open_jtalk.dll
      - run: ren library\lang\open_jtalk_lang.dll ${{ matrix.name }}_open_jtalk_lang.dll ; cp library\lang\${{ matrix.name }}_open_jtalk_lang.dll ${{ matrix.name }}_open_jtalk_lang.dll
      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ matrix.name }}_open_jtalk.dll
            ${{ matrix.name }}_open_jtalk_lang.dll

  buildWasm:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: sudo apt-get install csh -y && curl -O -L http://ftpmirror.gnu.org/automake/automake-1.15.tar.gz && tar -zxf automake-1.15.tar.gz && cd automake-1.15 && ./configure && make && sudo make install
    - name: Setup cache
      id: cache-system-libraries
      uses: actions/cache@v2
      with:
        path: ${{env.EM_CACHE_FOLDER}}
        key: ${{env.EM_VERSION}}-${{ runner.os }}
    - uses: mymindstorm/setup-emsdk@v10
      with:
        version: ${{env.EM_VERSION}}
        actions-cache-folder: ${{env.EM_CACHE_FOLDER}}
    - run: chmod +x ./build_wasm.sh && . ./build_wasm.sh
    - run: emar t library/lang/wasm-libopenjtalk-lang.a
    - name: Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          library/full/wasm-libopenjtalk.a
          library/lang/wasm-libopenjtalk-lang.a